name: CI - SGX ALL

on:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - "provers/sgx/**"
      - "!docs/**"
      - "script/build.sh"
      - "script/install.sh"
  pull_request:
    paths:
      - "provers/sgx/**"
      - "!docs/**"
      - "script/build.sh"
      - "script/install.sh"

jobs:
  build-test-sgx:
    name: Build and test sgx
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "sgx"
      version_toolchain: "stable"
      taskdb: “raiko-tasks/in-memory”

  integration-test-sgx:
    name: Run integration tests on sgx
    uses: ./.github/workflows/ci-integration-reusable.yml
    with:
      version_name: "sgx"
      version_toolchain: "nightly-2024-04-17"
      taskdb: “raiko-tasks/in-memory”

  build-test-sgx-docker:
    name: Build and test sgx with Docker
    uses: ./.github/workflows/ci-sgx-docker.yml

  build-test-sgx-hardware:
    name: Build and test sgx in hardware
    uses: ./.github/workflows/ci-sgx-hardware.yml
